IF
	InParty("Sharteel")
	!StateCheck("Sharteel",CD_STATE_NOTVALID) 
	InParty("Corwin")
	!StateCheck("Corwin",CD_STATE_NOTVALID) 
	See("Sharteel")
	See("Corwin")
	ActionListEmpty()
	!ActuallyInCombat()
	Global("k9SharteelCorwin","GLOBAL",4)
	!RealGlobalTimerExpired("k9SharteelCorwinTalk","GLOBAL")
THEN
	RESPONSE #100
		SetGlobal("k9SharteelCorwin","GLOBAL",5)
		StartDialogueNoSet([PC]) RealSetGlobalTimer("k9SharteelCorwinTalk","GLOBAL",1200)
END

