IF 
	Global("k9sharteelspawn","MYAREA",0)
	!BeenInParty("Sharteel")
	!Dead("sharteel")
THEN 
	RESPONSE #100
		SetGlobal("k9sharteelspawn","MYAREA",1)
		Lock("Door06")
		CreateCreature("k9sharte",[1225.307],SE)
		SmallWait(1)
		ActionOverride("sharteel",MakeGlobal())
		CreateCreature("k9sodfis",[1272.400],SE)
		Continue()
END


IF
	Global("Continuous_SoD_sharteel","MYAREA",0)
	OR(2)
		BeenInParty("sharteel")
		Exists("sharteel")
	!Dead("sharteel")
	!InPartyAllowDead("sharteel")
	!InParty("sharteel")
	!InMyArea("sharteel")
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		Lock("Door06")
		CreateCreature("k9sodfis",[1272.400],SE)
		SmallWait(1)
		SetGlobal("Continuous_SoD_sharteel","MYAREA",1)
		MoveGlobal("bd0104","sharteel",[1225.307])
		ApplySpellRES("bdresurr","sharteel")
		SmallWait(1)
		ApplySpellRES("bdrejuve","sharteel")
		ChangeEnemyAlly("sharteel",NEUTRAL)
		ChangeSpecifics("sharteel",ALLIES)
		ActionOverride("sharteel",SetGlobal("bd_joined","locals",0))
		ActionOverride("sharteel",SetGlobal("bd_retreat","locals",0))
		ActionOverride("sharteel",SetGlobal("bd_default_loc","locals",0))
		ActionOverride("sharteel",ChangeAIScript("k9shar",OVERRIDE))
		ActionOverride("sharteel",ChangeAIScript("DEFAULT",CLASS))
		ActionOverride("sharteel",ChangeAIScript("",RACE))
		ActionOverride("sharteel",ChangeAIScript("",GENERAL))
		ActionOverride("sharteel",ChangeAIScript("",DEFAULT))
		ActionOverride("sharteel",SetDialog("BDsharte"))
		ActionOverride("sharteel",Face(SE))
		SetInterrupt(TRUE)
		Continue()
END

IF
	Global("k9shar_unlock_door","GLOBAL",1)
THEN
	RESPONSE #100
		Unlock("Door06")
		OpenDoor("Door06")
		SetGlobal("k9shar_unlock_door","GLOBAL",2)
END
